Start epoch 0:
0it [00:04, ?it/s]
Traceback (most recent call last):
  File "/data/AI/Driver-Drowsiness-Android-App/ml/src/tools/train.py", line 115, in <module>
    main()
  File "/data/AI/Driver-Drowsiness-Android-App/ml/src/tools/train.py", line 112, in main
    train(args.ann, args.config)
  File "/data/AI/Driver-Drowsiness-Android-App/ml/src/tools/train.py", line 105, in train
    train_CNN_LSTM(train_data, val_data, epochs, device, config_obj["model_info"])
  File "/data/AI/Driver-Drowsiness-Android-App/ml/src/tools/train.py", line 74, in train_CNN_LSTM
    model, optimizer, train_loss_ep, val_loss_ep, val_acc_ep = epoch(model, train_data, val_data, loss_function, optimizer, device)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/AI/Driver-Drowsiness-Android-App/ml/src/tools/train.py", line 20, in epoch
    for i, (data, label) in tqdm(enumerate(train_loader)):
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 317, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 174, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 174, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hung/anaconda3/envs/hungnc/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 214, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [90, 720, 1280, 3] at entry 0 and [54, 720, 1280, 3] at entry 2
